version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directories:
      - "/"
      - "/shared/base/*"
      - "/tools/*"
    schedule:
      interval: "weekly"
