package tools

import (
	"crypto/rand"
	"errors"
	"fmt"
	"io"
	"io/fs"
	"os"
	"path/filepath"
	"strings"

	"github.com/dylanvgils/agentic-cli/internal/platform"
)

const (
	// maxInstructionsBytes caps reads of the agent-writable instructions file and snapshot
	maxInstructionsBytes = 1 << 20

	instructionsBeginMarker = "<!-- agentic:instructions:begin - auto-generated by `agentic run`, edits here are overwritten; add your own notes below the end marker instead -->"
	instructionsEndMarker   = "<!-- agentic:instructions:end -->"
)

// MergedInstructions returns hostPath's preserved content merged with block, without touching any files.
func MergedInstructions(toolHome, hostPath, block string) (string, error) {
	root, name, err := openToolsRoot(toolHome, hostPath)
	if errors.Is(err, fs.ErrNotExist) {
		return mergeInstructions("", block), nil
	}
	if err != nil {
		return "", err
	}
	defer func() { _ = root.Close() }()

	existing, err := readInstructions(root, name)
	if err != nil {
		return "", err
	}

	return mergeInstructions(existing, block), nil
}

// PrepareInstructionsSnapshot writes the merged content to a new, uniquely-named file in the OS temp dir, returning its path - so each run gets a private mount instead of sharing one live file.
func PrepareInstructionsSnapshot(toolHome, hostPath, block string) (string, error) {
	root, name, err := createToolsRoot(toolHome, hostPath)
	if err != nil {
		return "", err
	}
	defer func() { _ = root.Close() }()

	existing, err := readInstructions(root, name)
	if err != nil {
		return "", err
	}

	if err := ensureHostFile(root, name); err != nil {
		return "", err
	}

	f, err := os.CreateTemp("", "agentic-instructions-*"+filepath.Ext(hostPath))
	if err != nil {
		return "", err
	}
	defer func() { _ = f.Close() }()

	if _, err := f.WriteString(mergeInstructions(existing, block)); err != nil {
		_ = os.Remove(f.Name())
		return "", err
	}

	return f.Name(), nil
}

// FinalizeInstructionsSnapshot strips the managed block from snapshotPath and persists the rest back to hostPath, then removes snapshotPath.
func FinalizeInstructionsSnapshot(toolHome, hostPath, snapshotPath string) error {
	defer func() { _ = os.Remove(snapshotPath) }()

	f, err := os.Open(snapshotPath)
	if err != nil {
		return err
	}
	defer func() { _ = f.Close() }()

	content, err := readCapped(f, snapshotPath)
	if err != nil {
		return err
	}

	root, name, err := createToolsRoot(toolHome, hostPath)
	if err != nil {
		return err
	}
	defer func() { _ = root.Close() }()

	if err := root.MkdirAll(filepath.Dir(name), 0o750); err != nil {
		return err
	}

	return writeInstructions(root, name, stripManaged(content))
}

// stripManaged removes the agentic-managed block from existing, or returns it untouched if the markers are missing or malformed.
func stripManaged(existing string) string {
	begin := strings.Index(existing, instructionsBeginMarker)
	if begin == -1 {
		return existing
	}

	afterBegin := begin + len(instructionsBeginMarker)
	endOffset := strings.Index(existing[afterBegin:], instructionsEndMarker)
	if endOffset == -1 {
		return existing
	}

	end := afterBegin + endOffset + len(instructionsEndMarker)
	before := existing[:begin]
	after := strings.TrimLeft(existing[end:], "\n")

	return before + after
}

// writeManagedInstructions writes block into path, replacing only the managed section and leaving the rest untouched.
func writeManagedInstructions(toolHome, path, block string) error {
	root, name, err := createToolsRoot(toolHome, path)
	if err != nil {
		return err
	}
	defer func() { _ = root.Close() }()

	existing, err := readInstructions(root, name)
	if err != nil {
		return err
	}
	if existing == "" && block == "" {
		return nil
	}

	if err := root.MkdirAll(filepath.Dir(name), 0o750); err != nil {
		return err
	}
	return writeInstructions(root, name, mergeInstructions(existing, block))
}

// createToolsRoot is openToolsRoot, creating the tools dir first.
func createToolsRoot(toolHome, path string) (*os.Root, string, error) {
	if err := os.MkdirAll(filepath.Join(toolHome, ToolsDirName), 0o750); err != nil {
		return nil, "", err
	}
	return openToolsRoot(toolHome, path)
}

// openToolsRoot opens the tools dir under toolHome as a root and returns path relative to it, so a tool dir the agent swaps for a link can't lead reads or writes outside it.
func openToolsRoot(toolHome, path string) (*os.Root, string, error) {
	dir := filepath.Join(toolHome, ToolsDirName)
	name, err := filepath.Rel(dir, path)
	if err != nil || !filepath.IsLocal(name) {
		return nil, "", fmt.Errorf("%s is outside %s", path, dir)
	}

	root, err := os.OpenRoot(dir)
	if err != nil {
		return nil, "", err
	}
	return root, name, nil
}

// ensureHostFile creates name if missing, so Docker doesn't auto-create it as root when mounting the snapshot over it.
func ensureHostFile(root *os.Root, name string) error {
	if info, err := root.Lstat(name); err == nil {
		return checkRegular(name, info)
	} else if !os.IsNotExist(err) {
		return err
	}

	if err := root.MkdirAll(filepath.Dir(name), 0o750); err != nil {
		return err
	}

	// O_EXCL refuses to follow a dangling link to its target
	f, err := root.OpenFile(name, os.O_CREATE|os.O_EXCL|os.O_WRONLY, 0o640)
	if err != nil {
		return err
	}
	return f.Close()
}

// readInstructions reads name, empty when missing; the instructions file sits in the agent-writable tool home, so only a regular file is read.
func readInstructions(root *os.Root, name string) (string, error) {
	info, err := root.Lstat(name)
	if os.IsNotExist(err) {
		return "", nil
	}
	if err != nil {
		return "", err
	}
	if err := checkRegular(name, info); err != nil {
		return "", err
	}

	f, err := openRegular(root, name, info)
	if err != nil {
		return "", err
	}
	defer func() { _ = f.Close() }()

	return readCapped(f, name)
}

// openRegular opens name and refuses it unless it is still the regular file checked, so a link or FIFO swapped in after Lstat can't redirect or hang the read.
func openRegular(root *os.Root, name string, checked os.FileInfo) (*os.File, error) {
	f, err := platform.OpenInRoot(root, name)
	if err != nil {
		return nil, err
	}

	opened, err := f.Stat()
	if err == nil && (!opened.Mode().IsRegular() || !os.SameFile(checked, opened)) {
		err = fmt.Errorf("%s changed while reading it", name)
	}
	if err != nil {
		_ = f.Close()
		return nil, err
	}
	return f, nil
}

// readCapped reads r up to maxInstructionsBytes, so an agent-written file can't exhaust host memory.
func readCapped(r io.Reader, path string) (string, error) {
	data, err := io.ReadAll(io.LimitReader(r, maxInstructionsBytes+1))
	if err != nil {
		return "", err
	}
	if len(data) > maxInstructionsBytes {
		return "", fmt.Errorf("%s is larger than %d bytes", path, maxInstructionsBytes)
	}
	return string(data), nil
}

// writeInstructions replaces name via a temp file and rename, so a planted symlink is replaced instead of followed.
func writeInstructions(root *os.Root, name, content string) error {
	tmp := filepath.Join(filepath.Dir(name), ".agentic-instructions-"+rand.Text())
	f, err := root.OpenFile(tmp, os.O_CREATE|os.O_EXCL|os.O_WRONLY, 0o600)
	if err != nil {
		return err
	}
	defer func() { _ = root.Remove(tmp) }()

	_, err = f.WriteString(content)
	if err == nil {
		// On the handle, since the agent can swap the temp name for a link
		err = f.Chmod(0o640)
	}
	if err != nil {
		_ = f.Close()
		return err
	}

	if err := f.Close(); err != nil {
		return err
	}
	return root.Rename(tmp, name)
}

// checkRegular refuses anything but a regular file, such as a symlink the agent planted to redirect a host read or write.
func checkRegular(path string, info os.FileInfo) error {
	if !info.Mode().IsRegular() {
		return fmt.Errorf("%s is not a regular file; remove it and run again", path)
	}
	return nil
}

// mergeInstructions returns existing with its managed block replaced by block, or removed when block is empty.
func mergeInstructions(existing, block string) string {
	rest := stripManaged(existing)

	var b strings.Builder
	if block != "" {
		b.WriteString(instructionsBeginMarker + "\n")
		b.WriteString(strings.TrimSuffix(block, "\n"))
		b.WriteString("\n" + instructionsEndMarker + "\n")
		if rest != "" {
			b.WriteString("\n")
		}
	}
	b.WriteString(rest)

	return b.String()
}
