package tools

import (
	"os"
	"path/filepath"
	"strings"
)

const (
	instructionsBeginMarker = "<!-- agentic:instructions:begin - auto-generated by `agentic run`, edits here are overwritten; add your own notes below the end marker instead -->"
	instructionsEndMarker   = "<!-- agentic:instructions:end -->"
)

// MergedInstructions returns hostPath's preserved content merged with block, without touching any files.
func MergedInstructions(hostPath, block string) (string, error) {
	existing, err := os.ReadFile(hostPath)
	if err != nil && !os.IsNotExist(err) {
		return "", err
	}

	return mergeInstructions(string(existing), block), nil
}

// PrepareInstructionsSnapshot writes the merged content to a new, uniquely-named file in the OS temp dir, returning its path - so each run gets a private mount instead of sharing one live file.
func PrepareInstructionsSnapshot(hostPath, block string) (string, error) {
	merged, err := MergedInstructions(hostPath, block)
	if err != nil {
		return "", err
	}

	if err := ensureHostFile(hostPath); err != nil {
		return "", err
	}

	f, err := os.CreateTemp("", "agentic-instructions-*"+filepath.Ext(hostPath))
	if err != nil {
		return "", err
	}
	defer func() { _ = f.Close() }()

	if _, err := f.WriteString(merged); err != nil {
		_ = os.Remove(f.Name())
		return "", err
	}

	return f.Name(), nil
}

// ensureHostFile creates hostPath if missing, so Docker doesn't auto-create it as root when mounting the snapshot over it.
func ensureHostFile(hostPath string) error {
	if _, err := os.Stat(hostPath); err == nil {
		return nil
	} else if !os.IsNotExist(err) {
		return err
	}

	if err := os.MkdirAll(filepath.Dir(hostPath), 0o750); err != nil {
		return err
	}
	return os.WriteFile(hostPath, nil, 0o640)
}

// FinalizeInstructionsSnapshot strips the managed block from snapshotPath and persists the rest back to hostPath, then removes snapshotPath.
func FinalizeInstructionsSnapshot(hostPath, snapshotPath string) error {
	defer func() { _ = os.Remove(snapshotPath) }()

	content, err := os.ReadFile(snapshotPath)
	if err != nil {
		return err
	}

	preserved := stripManaged(string(content))
	if err := os.MkdirAll(filepath.Dir(hostPath), 0o750); err != nil {
		return err
	}

	return os.WriteFile(hostPath, []byte(preserved), 0o640)
}

// stripManaged removes the agentic-managed block from existing, or returns it untouched if the markers are missing or malformed.
func stripManaged(existing string) string {
	begin := strings.Index(existing, instructionsBeginMarker)
	if begin == -1 {
		return existing
	}

	afterBegin := begin + len(instructionsBeginMarker)
	endOffset := strings.Index(existing[afterBegin:], instructionsEndMarker)
	if endOffset == -1 {
		return existing
	}

	end := afterBegin + endOffset + len(instructionsEndMarker)
	before := existing[:begin]
	after := strings.TrimLeft(existing[end:], "\n")

	return before + after
}

// writeManagedInstructions writes block into path, replacing only the managed section and leaving the rest untouched.
func writeManagedInstructions(path, block string) error {
	existing, err := os.ReadFile(path)
	if err != nil {
		if !os.IsNotExist(err) {
			return err
		}
		if block == "" {
			return nil
		}
	}

	return os.WriteFile(path, []byte(mergeInstructions(string(existing), block)), 0o640)
}

// mergeInstructions returns existing with its managed block replaced by block, or removed when block is empty.
func mergeInstructions(existing, block string) string {
	rest := stripManaged(existing)

	var b strings.Builder
	if block != "" {
		b.WriteString(instructionsBeginMarker + "\n")
		b.WriteString(strings.TrimSuffix(block, "\n"))
		b.WriteString("\n" + instructionsEndMarker + "\n")
		if rest != "" {
			b.WriteString("\n")
		}
	}
	b.WriteString(rest)

	return b.String()
}
