package tools

import (
	"os"
	"path/filepath"
	"strings"
)

const (
	instructionsBeginMarker = "<!-- agentic:instructions:begin - auto-generated by `agentic run`, edits here are overwritten; add your own notes below the end marker instead -->"
	instructionsEndMarker   = "<!-- agentic:instructions:end -->"
)

// MergedInstructions reads hostPath's preserved content (its existing content
// minus any managed block) and merges it with block, returning the combined
// result - the effective content a run would write into the tool's
// instructions file, without touching any files. Shared by
// PrepareInstructionsSnapshot and by `agentic instructions <tool>`, which
// previews this same result without starting a container.
func MergedInstructions(hostPath, block string) (string, error) {
	existing, err := os.ReadFile(hostPath)
	if err != nil && !os.IsNotExist(err) {
		return "", err
	}

	return mergeInstructions(string(existing), block), nil
}

// PrepareInstructionsSnapshot merges hostPath's preserved content (its existing
// content minus any managed block) with block, and writes the result to a new,
// uniquely-named file in the OS temp dir, returning its path. Mounting this single
// file over the tool's instructions path in the container gives each run a private
// view for its whole session, so concurrent runs of the same tool never share one
// live, mutable file.
func PrepareInstructionsSnapshot(hostPath, block string) (string, error) {
	merged, err := MergedInstructions(hostPath, block)
	if err != nil {
		return "", err
	}

	f, err := os.CreateTemp("", "agentic-instructions-*"+filepath.Ext(hostPath))
	if err != nil {
		return "", err
	}
	defer func() { _ = f.Close() }()

	if _, err := f.WriteString(merged); err != nil {
		_ = os.Remove(f.Name())
		return "", err
	}

	return f.Name(), nil
}

// FinalizeInstructionsSnapshot reads back snapshotPath - possibly changed by the
// tool during the run (e.g. Claude Code's own memory feature) - strips the now-stale
// managed block, and persists whatever organic content remains to hostPath (even
// when that's nothing), so the next run regenerates a fresh managed block on top of
// it. hostPath itself is never removed - only snapshotPath is, always.
func FinalizeInstructionsSnapshot(hostPath, snapshotPath string) error {
	defer func() { _ = os.Remove(snapshotPath) }()

	content, err := os.ReadFile(snapshotPath)
	if err != nil {
		return err
	}

	preserved := stripManaged(string(content))
	if err := os.MkdirAll(filepath.Dir(hostPath), 0o750); err != nil {
		return err
	}

	return os.WriteFile(hostPath, []byte(preserved), 0o640)
}

// stripManaged removes the agentic-managed block (markers included) from existing
// file content, returning whatever is left. If the markers are missing, malformed,
// or out of order, the entire content is returned untouched to avoid ever losing
// data.
func stripManaged(existing string) string {
	begin := strings.Index(existing, instructionsBeginMarker)
	if begin == -1 {
		return existing
	}

	afterBegin := begin + len(instructionsBeginMarker)
	endOffset := strings.Index(existing[afterBegin:], instructionsEndMarker)
	if endOffset == -1 {
		return existing
	}

	end := afterBegin + endOffset + len(instructionsEndMarker)
	before := existing[:begin]
	after := strings.TrimLeft(existing[end:], "\n")

	return before + after
}

// writeManagedInstructions writes block into the file at path, replacing only the
// content between the agentic markers and leaving everything else untouched - the
// user's own notes, or anything the tool itself appended at runtime (e.g. Claude
// Code's own memory feature). An empty block removes the managed section entirely
// rather than leaving empty markers behind.
func writeManagedInstructions(path, block string) error {
	existing, err := os.ReadFile(path)
	if err != nil {
		if !os.IsNotExist(err) {
			return err
		}
		if block == "" {
			return nil
		}
	}

	return os.WriteFile(path, []byte(mergeInstructions(string(existing), block)), 0o640)
}

// mergeInstructions returns existing with its managed block (if any) replaced by
// block, or removed entirely when block is empty - the pure merge step shared by
// writeManagedInstructions and the snapshot functions above.
func mergeInstructions(existing, block string) string {
	rest := stripManaged(existing)

	var b strings.Builder
	if block != "" {
		b.WriteString(instructionsBeginMarker + "\n")
		b.WriteString(strings.TrimSuffix(block, "\n"))
		b.WriteString("\n" + instructionsEndMarker + "\n")
		if rest != "" {
			b.WriteString("\n")
		}
	}
	b.WriteString(rest)

	return b.String()
}
