package cmd

import (
	"fmt"
	"os"

	"github.com/dylanvgils/agentic-cli/internal/tools"
	"github.com/spf13/cobra"
)

func init() {
	rootCmd.AddCommand(aliasesCmd)
}

var aliasesCmd = &cobra.Command{
	Use:       "aliases [shell]",
	Short:     "Print shell alias definitions for installed tools",
	Long:      "Print shell alias definitions for installed tools. Supported shells: bash, zsh (default).\nSource the output to activate aliases.",
	Args:      cobra.MatchAll(cobra.MaximumNArgs(1), cobra.OnlyValidArgs),
	ValidArgs: []string{"bash", "zsh"},
	RunE:      runAliases,
}

func runAliases(_ *cobra.Command, args []string) error {
	shell := "zsh"
	if len(args) > 0 {
		shell = args[0]
	}

	switch shell {
	case "zsh":
		fmt.Println("# agentic tool aliases - generated by: agentic aliases zsh")
		fmt.Println("# Add to .zshrc:  source <(agentic aliases)")
	case "bash":
		fmt.Println("# agentic tool aliases - generated by: agentic aliases bash")
		fmt.Println("# Add to .bashrc:  source <(agentic aliases bash)")
	}

	for _, name := range tools.Names() {
		image, err := tools.ImageName(name)
		if err != nil {
			return err
		}

		info, err := inspectImage(image)
		if err != nil {
			return err
		}

		if info != nil {
			if _, err := fmt.Fprintf(os.Stdout, "alias %s='agentic %s'\n", name, name); err != nil {
				return err
			}
		}
	}

	return nil
}
